### ISSUE TITLE
Login Link from Sign up Page routes nowhere

### ISSUE THREAD

**Issue by Mishel-T** [Mishel-T/travelRush2#102]
From the sign up page, you have the ability to login instead of signing up. 
When you click 'Login Here' from the Sign up page, the system routes to a /login url, but there is nothing there. The link should open the login modal. 
The login modal can be found in the Modal component and is Emma's code. 
Essentially it should do what the login button on the homepage does.

**Comment by Chuyloops14** [comment]
i suck at coding

**Comment by Mishel-T** [comment]
Jesus please push your code again for this resolution. Remember we had to undo your merge since it overwrote some of Emma's fixes.
