### ISSUE TITLE
Account Successfully Created - Cosmetic Issue

### ISSUE THREAD

**Issue by Mishel-T** [Mishel-T/travelRush2#104]
When registering for an account from the Sign Up page and the data is successfully saved (to DB), user gets an 'Account Successfully Created' message at the bottom of the sign up page, but the message displays in black font so it blends in with the sign up page background. Need to update this text. --- note: might be moot, if Dupe ends up routing the user immediately to their My Account page on sign up. So maybe save this one to the end.

**Comment by delzerbear** [comment]
On what page is the code for the message? Thanks.

**Comment by delzerbear** [comment]
Fixed by Dupe's routing. Closing issue.
