### ISSUE TITLE
Alignment off

### ISSUE THREAD

**Issue by Mishel-T** [Mishel-T/travelRush2#70]
Alignment of Submit button for search on main page is off. 
Cards are also out of alignment. Don't always display in one row.

**Comment by delzerbear** [comment]
Submit button in SearchForm has been taken care of. 
Beginning work on Cards.

**Comment by delzerbear** [comment]
Column class sizes have been applied to cards. Minor bug that can be shipped out: Weather card is a few pixels shorter then other ones, but hardly noticeable.
